import Fader from './Fader.js';
import AfterImage from './AfterImage.js';
import Drawer from './Drawer.js';
import ScrollableLabelArea from './ScrollableLabelArea.js';
import ScrollLayer from './ScrollLayer.js';
import PetalShape from './PetalShape.js';
import DashedLineShape from './DashedLineShape.js';
import AnimationSprite from './AnimationSprite.js';
import Sequence from './Sequence.js';
import extendWorldCollision from './extendWorldCollision.js';
phina.register('phina.accessory.Fader', Fader);
phina.register('phina.accessory.AfterImage', AfterImage);
phina.register('phina.accessory.Drawer', Drawer);
phina.register('phina.ui.ScrollableLabelArea', ScrollableLabelArea);
phina.register('phina.display.ScrollLayer', ScrollLayer);
phina.register('phina.display.PetalShape', PetalShape);
phina.register('phina.display.DashedLineShape', DashedLineShape);
phina.register('phina.display.AnimationSprite', AnimationSprite);
phina.register('phina.game.Sequence', Sequence);
phina.register('phina.extendWorldCollision', extendWorldCollision);
